import = [
    "/home/chpw/.config/alacritty/themes/themes/rainbow.toml"
]
live_config_reload = true


[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 16

[font.bold]
family = "FiraCode Nerd font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[window]
opacity = 0.7

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 0
y = 0
